### ISSUE TITLE
IdleToken Version

### ISSUE THREAD

**Issue by Sam-Devs** [Idle-Labs/idle-contracts#25]
I would like to know the version of IdleToken is up to date for implementation.
I asked because we would like to integrate Idle Protocol into our service and we are looking forward to using IdleToken contract file (which has the underlying factors of the protocol) and turning the functions/methods into APIs.

**Comment by bugduino** [comment]
Here you can find all addresses for idleTokens https://developers.idle.finance/contracts-and-codebase
