### ISSUE TITLE
IdleTokens ABIs

### ISSUE THREAD

**Issue by Sam-Devs** [Idle-Labs/idle-contracts#26]
Please can you point me to where the ABIs for all the tokens (IdleDAI, IdleWETH, IdleUSDC, IdleUSTC, etc) are?
I checked etherscan for the ABIs but I was not sure of what I saw.
Thanks.

**Comment by bugduino** [comment]
Hi, you can use this one https://www.github.com/Idle-Labs/idle-contracts/tree/develop/abi%2FIdleTokenGovernance.json

**Comment by Sam-Devs** [comment]
I mean this contains all the the abis for all the tokens?

**Comment by bugduino** [comment]
The abi Is the same for all idleTokens
