### ISSUE TITLE
"truffle test" leads to failed tests due to "out of gas"

### ISSUE THREAD

**Issue by SMLaursen** [Idle-Labs/idle-contracts#30]
Hi Idle Labs

On commit 773f1b2cf04f48572fe198b7caa4c63973722130, the **Tests** section in README.md makes all tests in _Contract: IdleTokenV3_1 fail_ due to "out of gas" on the following setup :

OS : Win10 Home 21H1 x64
Node.js : 14.17.5 (x64)
NPM : 6.14.14
Truffle : 5.4.6
Ganache CLI : v6.12.2 (ganache-core: 2.13.2)

Using the following parameters for  **truffle-config.js** : 
`   test: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*',
      gas: 10000000,
      gasPrice: 50 * 1e9, // 50 gwei
    },`

as well as reducing the optimizer runs from 999999 to 200 by setting :
`optimizer: {
  enabled: true,
  runs: 200
}`

while starting ganache with a larger blocksize :
`ganache-cli --allowUnlimitedContractSize --l  10000000`

Makes the tests runnable on my system. I'm new to the development stack so these settings are more or less derived using trial and error. So I'm not sure what the correct solution is and whether they all effect my inability to run the test-suite.

**Comment by bugduino** [comment]
Hey,
thanks for reaching out, I think there is a wrong `runs` parameter in the truffle-config.js (otherwise `IdleTokenGovernance.sol` contract would be over sized) The number of runs should be set to `1`. I added a commit with the fix.

Btw tests in this repo should always be done against a ganache-cli with the ```--allowUnlimitedContractSize``` flag

**Comment by SMLaursen** [comment]
Thanks for the prompt feedback. Now I'm able to run the first four tests of IdleTokenV3_1 - but still not the full testsuite using simply :
`ganache-cli --allowUnlimitedContractSize`
followed by
`truffle test`

> Contract: IdleBatchConverter
>     √ constructor set rebalanceManager addr (204ms)
>     √ cannot withdraw before first migration (1703ms)
>     √ single user migration (1830ms)
>     √ multiple user migration, single batch (2649ms)
>     √ multiple user migration, multiple batch (6998ms)
> 
>   Contract: IdleTokenV3_1
>     √ initialize set a name (262ms)
>     √ initialize set a symbol (292ms)
>     √ initialize set a decimals (273ms)
>     √ initialize set a token (DAI) address (241ms)
>     1) "before each" hook for "initialize set a rebalancer address"
> 
>   Contract: MinimalInitializableProxyFactory
>     2) "before all" hook: prepare suite for "deploys a minimal proxy and initializes it"
> 
>   Contract: IdleCompound
>     3) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleCompoundETH
>     4) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleCompoundV2
>     5) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleDSR
>     6) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleDyDx
>     7) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleFulcrum
>     8) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleFulcrumDisabled
>     9) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleFulcrumV2
>     10) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleAave
>     11) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: IdleAaveV2
>     12) "before all" hook: prepare suite for "constructor set a token address"
> 
>   Contract: yxToken
>     13) "before all" hook: prepare suite for "constructor set a underlying address"
> 
> 
>   9 passing (2m)
>   13 failing
> 
>   1) Contract: IdleTokenV3_1
>        "before each" hook for "initialize set a rebalancer address":
> 
> Could not connect to your Ethereum client with the following parameters:
>     - host       > 127.0.0.1
>     - port       > 8545
>     - network_id > 1629105074596
> Please check that your Ethereum client:
>     - is running
>     - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
>     - is accessible over the network
>     - is properly configured in your Truffle configuration file (truffle-config.js)
> 
>   ProviderError:
>       at Context.<anonymous> (test\IdleTokenV3_1.js:87:25)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ...

**Comment by bugduino** [comment]
Seems to be an issue with ganache-cli which is basically stopping apparently, what's your ganache-cli version?

Could you try to launch this test directly ```truffle test ./test/IdleTokenV3_1.js``` ?

I'm able to go on on my side 
```  
Contract: IdleTokenV3_1
    ✓ initialize set a name
    ✓ initialize set a symbol
    ✓ initialize set a decimals
    ✓ initialize set a token (DAI) address (83ms)
    ✓ initialize set a rebalancer address (66ms)
    ✓ initialize set owner
    ✓ initialize set pauser (69ms)
    ✓ manualInitialize set stuff (299ms)
    ✓ _init set stuff (155ms)
    ✓ setAllAvailableTokensAndWrappers (478ms)
    ✓ allows onlyOwner to setRebalancer (243ms)
    ✓ allows onlyOwner to setOracleAddress (203ms)
    ✓ allows onlyOwner to setFeeAddress (259ms)
    ✓ allows onlyOwner to setFee (261ms)
    ✓ allows onlyOwner to setMaxUnlentPerc (183ms)
    ✓ calculates current tokenPrice when IdleToken supply is 0 (64ms)
    ✓ calculates current tokenPrice when funds are all in one (2306ms)
    ✓ calculates current tokenPrice when funds are all in one pool (2972ms)
    ✓ calculates current tokenPrice when funds are in different pools (3480ms)
...

``` 
(Still going on it's a 'bit' slow)

I'm using `Ganache CLI v6.12.1 (ganache-core: 2.13.1)`

**Comment by SMLaursen** [comment]
Though it appears it's an issue with ganache, I sometimes get messages related to "out of gas" why I believe this is the underlying cause.

My setup is;
OS : Win10 Home 21H1 x64
Node.js : 14.17.5 (x64)
NPM : 6.14.14
Truffle : 5.4.6
Ganache CLI : v6.12.2 (ganache-core: 2.13.2)

Aha, calling `truffle test ./test/IdleTokenV3_1.js` directly appears to make the test-suite runnable:

>  Contract: IdleTokenV3_1
    √ initialize set a name (173ms)
    √ initialize set a symbol (357ms)
    √ initialize set a decimals (355ms)
    √ initialize set a token (DAI) address (154ms)
    √ initialize set a rebalancer address (200ms)
    √ initialize set owner (257ms)
    √ initialize set pauser (276ms)
    √ manualInitialize set stuff (1980ms)
    √ _init set stuff (411ms)
    √ setAllAvailableTokensAndWrappers (2969ms)
    √ allows onlyOwner to setRebalancer (1005ms)
    √ allows onlyOwner to setOracleAddress (894ms)
    √ allows onlyOwner to setFeeAddress (979ms)
    √ allows onlyOwner to setFee (1148ms)
    √ allows onlyOwner to setMaxUnlentPerc (1241ms)
    √ calculates current tokenPrice when IdleToken supply is 0 (277ms)
    √ calculates current tokenPrice when funds are all in one (9339ms)
...

**Comment by bugduino** [comment]
Glad it worked. I got that error too in the past when running the whole suite, but I'm not really sure about the root cause, inside ganache-cli
