### ISSUE TITLE
Review CompoundETH

### ISSUE THREAD

**Issue by emilianobonassi** [Idle-Labs/idle-contracts#7]
https://forum.dao.reviews/t/idle-finance-aave-v2-wrapper-review-ask/69

Below my reccomendations

1. Use `underlying` or `weth` not both.

https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/wrappers/IdleCompoundETH.sol#L30-L45

To be gas efficient, also at deploy time, remove _underlying constructor param and declare underlying field constant with the weth value.

2. Use `underlying`

https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/wrappers/IdleCompoundETH.sol#L173

https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/wrappers/IdleCompoundETH.sol#L200

3. Can be oneliner

https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/wrappers/IdleCompoundETH.sol#L175-L177

4. Do not repeat `IERC20(token)`

https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/wrappers/IdleCompoundETH.sol#L179-L181

5. Can be oneliner (do not declare _cToken)

https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/wrappers/IdleCompoundETH.sol#L195-L198

**Comment by bugduino** [comment]
Fixed [here](https://github.com/Idle-Labs/idle-contracts/commit/89baf3a5184943f08a1408f78be83259a1dfb065), let me know what do you think

**Comment by emilianobonassi** [comment]
Great @bugduino, LGTM closing the issue 🤝

**Comment by emilianobonassi** [comment]
Anyway, I suggest to remove the following since you do the check in the upper layer and improved in the other review ;)

https://github.com/Idle-Labs/idle-contracts/blob/develop/contracts/wrappers/IdleCompoundETH.sol#L167-L169

It could be also a oneliner.

**Comment by bugduino** [comment]
Added commit for the redeem [here](https://github.com/Idle-Labs/idle-contracts/commit/6735c559281519ed2c8760e14e55097aef3170a0) (Removed also `IdleCompoundETHNoConst` which is not needed anymore)

**Comment by emilianobonassi** [comment]
Great LGTM! :handshake:
